services:
    ppl_auth_bot:
        container_name: ppl_auth_bot
        volumes:
            - ./data:/app/data
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - nginx
        environment:
            - TZ=Europe/Moscow
        restart: always
        command: npm run start

networks:
    nginx:
        external: true
        name: nginx
